# -*- coding: utf-8 -*-
"""Text & Audio_Features_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vx9IZBsQYGu-PR2QDnPqCTrxDRXMhDwU
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd
import librosa
import numpy as np
from pathlib import Path
from scipy.stats import skew, kurtosis

"""# Text Features
Already provided in the raw ELEA dataset file (Sanchez-Cortes et al. (2012))
"""

text_ff = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/transcriptions/LIWC_categories/outputs_LIWC_perPart_FULLTranscription.csv')
text_ff.shape
text_ff.columns

# Demographic File (also provided in the raw dataset)
demo = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/questionnaires/personality_gender_age.csv')
demo.shape
demo.columns

# Combine Demo file and text file so that I get one file with gender info and age regarding each participant along with its Linguistic features and predicted Big Five traits
text_and_demo = pd.merge(text_ff, demo, on=['group', 'letterId'], how='outer')
text_and_demo.shape
text_and_demo.columns
text_and_demo.head()

# Step 1: Standardize the Gender column to 'Female' and 'Male'

text_and_demo['Gender'] = text_and_demo['Gender'].str.lower().replace({'female': 'Female', 'male': 'Male', 'f': 'Female', 'm': 'Male'}).fillna('Unknown')

# Step 2: Calculate median age for each gender
median_age_male = text_and_demo[text_and_demo['Gender'] == 'Male']['Age'].median()
median_age_female = text_and_demo[text_and_demo['Gender'] == 'Female']['Age'].median()

# Step 3: Fill null values in Age column with gender-specific median
text_and_demo = text_and_demo.copy()
text_and_demo.loc[text_and_demo['Gender'] == 'Male', 'Age'] = text_and_demo.loc[text_and_demo['Gender'] == 'Male', 'Age'].fillna(median_age_male)
text_and_demo.loc[text_and_demo['Gender'] == 'Female', 'Age'] = text_and_demo.loc[text_and_demo['Gender'] == 'Female', 'Age'].fillna(median_age_female)

# Save the newly merged file
text_and_demo.to_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/text_and_demo.csv', index=False)
text_and_demo.shape
text_and_demo.columns
text_and_demo.head()

"""# Audio Features"""

from pathlib import Path
import re

# Path to peakingSegmentation folder
folder_path = Path('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/audio/SpeakingSegmentation')

for csv_file in folder_path.glob('*.csv'):
    print(csv_file.name)

for i in range(21, 41):
    file_pattern = f"*G{i}.csv"
    for csv_file in folder_path.glob(file_pattern):
      df = pd.read_csv(csv_file, skiprows=2)
      df.to_csv(csv_file, index=False)

g6_df = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/audio/SpeakingSegmentation/20091109-144229_G6.csv')
g6_df['person'] = g6_df['person'].replace('M6M0911M', 'M')
#g6_df.head(20)

from pathlib import Path
import re

# Path to peakingSegmentation folder
folder_path = Path('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/audio/SpeakingSegmentation')

#for csv_file in folder_path.glob('*.csv'):
 #   print(csv_file.name)

import librosa
import numpy as np
import pandas as pd
from pathlib import Path
from tqdm import tqdm
from scipy.stats import skew, kurtosis

audio_base = Path('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/audio')
segmentation_base = audio_base / 'SpeakingSegmentation'
wav_base = audio_base / 'Groups1-40_wav'

# Output directory
output_base = audio_base.parent / 'processed_features'
output_base.mkdir(parents=True, exist_ok=True)

def extract_group_number(filename):
    """Extract group number from filename (e.g., G20 from 20100408-160401_G20.csv)"""
    try:
        return int(filename.stem.split('_G')[-1])
    except (IndexError, ValueError):
        return None

def extract_audio_features(csv_file):
    """Extract audio features for each person in the CSV file"""
    try:
        # Extract group number from CSV filename
        group_num = extract_group_number(csv_file)
        if group_num is None:
            return pd.DataFrame()

        # Load segmentation data
        seg_file = csv_file
        df = pd.read_csv(seg_file)

        # Load audio file
        audio_file = wav_base / f'group{group_num}.wav'
        if not audio_file.exists():
            print(f"WAV file not found: {audio_file}")
            return pd.DataFrame()

        y, sr = librosa.load(audio_file, sr=None)

        # Group segments by person
        grouped = df.groupby('person')

        features = []
        for person, group in grouped:
            # Combine all segments for this person
            segments = [y[int(row['start']*sr):int(row['end']*sr)]
                       for _, row in group.iterrows() if row['start'] < row['end']]
            if not segments:
                continue
            combined_segment = np.concatenate(segments)

            # Extract comprehensive audio features
            audio_features = extract_comprehensive_features(combined_segment, sr)
            audio_features['person'] = person
            audio_features['group'] = group_num
            audio_features['file_name'] = csv_file.name
            features.append(audio_features)

        return pd.DataFrame(features)

    except Exception as e:
        return pd.DataFrame()

def extract_comprehensive_features(segment, sr):
    """Extract comprehensive audio features from a segment"""
    features = {}

    # Pitch features
    f0, voiced_flag, _ = librosa.pyin(segment, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'))
    f0 = f0[voiced_flag]
    features.update({
        'pitch_mean': np.mean(f0) if len(f0) > 0 else 0,
        'pitch_std': np.std(f0) if len(f0) > 0 else 0,
        'pitch_range': np.ptp(f0) if len(f0) > 0 else 0,
        'pitch_skew': skew(f0) if len(f0) > 2 else 0,
        'pitch_kurtosis': kurtosis(f0) if len(f0) > 3 else 0
    })

    # Intensity/Energy features
    rms = librosa.feature.rms(y=segment)[0]
    features.update({
        'intensity_mean': np.mean(rms) if len(rms) > 0 else 0,
        'intensity_std': np.std(rms) if len(rms) > 0 else 0,
        'intensity_max': np.max(rms) if len(rms) > 0 else 0,
        'intensity_min': np.min(rms) if len(rms) > 0 else 0
    })

    # Temporal features
    duration = librosa.get_duration(y=segment, sr=sr)
    features.update({
        'speaking_duration': duration,
        'speaking_rate': len(segment)/duration if duration > 0 else 0,
        'articulation_rate': len(librosa.effects.preemphasis(segment))/duration if duration > 0 else 0
    })

    # Spectral features
    spectral_centroid = librosa.feature.spectral_centroid(y=segment, sr=sr)[0]
    spectral_bandwidth = librosa.feature.spectral_bandwidth(y=segment, sr=sr)[0]
    features.update({
        'spectral_centroid_mean': np.mean(spectral_centroid) if len(spectral_centroid) > 0 else 0,
        'spectral_centroid_std': np.std(spectral_centroid) if len(spectral_centroid) > 0 else 0,
        'spectral_bandwidth_mean': np.mean(spectral_bandwidth) if len(spectral_bandwidth) > 0 else 0,
        'spectral_bandwidth_std': np.std(spectral_bandwidth) if len(spectral_bandwidth) > 0 else 0
    })

    # Voice quality features
    harmonic_ratio = librosa.effects.harmonic(segment)
    features.update({
        'harmonic_ratio': np.mean(harmonic_ratio) if len(harmonic_ratio) > 0 else 0,
        'noise_ratio': 1 - np.mean(harmonic_ratio) if len(harmonic_ratio) > 0 else 1
    })

    return features

# Find all CSV files in the segmentation directory
csv_files = list(segmentation_base.glob('*.csv'))

# Process all CSV files
all_features = []
for csv_file in tqdm(csv_files, desc="Processing files"):
    group_features = extract_audio_features(csv_file)
    if not group_features.empty:
        all_features.append(group_features)

# Combine all features
if all_features:
    audio_features_df = pd.concat(all_features, ignore_index=True)

    # Save audio features to CSV
    audio_features_file = output_base / 'audio_features.csv'
    audio_features_df.to_csv(audio_features_file, index=False)

# Now combine these audio features w/ text_demo file
audio_features_df = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/processed_features/audio_features.csv')
audio_features_df.columns
import pandas as pd

audio_features_path = '/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/processed_features/audio_features.csv'
output_path = '/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/combined_features.csv'

#Left join to ensure all content of textLIWC_demo file is there and only the matching ones from Audio files due to missing data
combined_df = pd.merge(
    text_and_demo,
    audio_features_df,
    how='left',
    left_on=['group', 'letterId'],
    right_on=['group', 'person'],
    validate='one_to_one'
)

combined_df.to_csv(output_path, index=False)

# -*- coding: utf-8 -*-
"""
Calculate Pearson correlations between acoustic features and Big Five personality traits
and visualize as a heatmap.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset (adjust path as needed)
master_df = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/combined_features_with_transcripts.csv')

# Define acoustic features and Big Five personality traits
acoustic_features = ['pitch_mean', 'pitch_std', 'pitch_range', 'intensity_mean',
                     'intensity_std', 'spectral_centroid_mean', 'spectral_centroid_std',
                     'speaking_rate']
target_cols = ['EXTROV.MEDIA.NEO', 'NEUROTIC.MEDIA.NEO', 'OPENNESS.MEDIA.NEO',
               'AGREAB.MEDIA.NEO', 'CONSCIENT.MEDIA.NEO']

# Filter DataFrame to include only relevant columns and drop rows with missing values
data = master_df[acoustic_features + target_cols].dropna()

# Calculate Pearson correlation matrix
correlation_matrix = data.corr(method='pearson')

# Extract correlations between acoustic features and personality traits
corr_acoustic_traits = correlation_matrix.loc[acoustic_features, target_cols]

# Create heatmap visualization
plt.figure(figsize=(10, 6))
sns.heatmap(corr_acoustic_traits, annot=True, cmap='coolwarm', center=0,
            vmin=-1, vmax=1, fmt='.2f')
plt.title('Correlation Between Acoustic Features and Big Five Personality Traits')
plt.xlabel('Personality Traits')
plt.ylabel('Acoustic Features')
plt.tight_layout()

# Save the plot for inclusion in the paper
plt.savefig('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/correlation_heatmap.png', dpi=300)
plt.close()

# Print correlation matrix for reference
print("Correlation Matrix (Acoustic Features vs. Big Five Traits):")
print(corr_acoustic_traits)

