# -*- coding: utf-8 -*-
"""Text,Audio,FusionModeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B8K6qI0sqB62ebSDb0ohSM2845_YoNw
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Data Preprocessing"""

# Add raw transcriptions for each group member to our master feature file
from pathlib import Path
import re
import pandas as pd

# Raw Transcription files folder
trans_folder_path = Path('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/transcriptions/Transcription_txtFiles')
letter_map_file = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/4573018/elea 2/transcriptions/LettersandIdSpeaker.csv')
transcriptions = []

def extract_transcripts(file_path, group_id, speaker_map):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            text = f.read()
            pattern = r'(\d+:\d+:\d+(?:\.\d+)?)\t([^\t]+)\t(.*?)(?=\n\d+:\d+:\d+(?:\.\d+)?|\Z)'
            matches = re.findall(pattern, text, re.DOTALL)
            speaker_transcripts = {}
            for _, speaker, transcript in matches:
                transcript = transcript.strip()
                if transcript and not re.match(r'^\(.*\)$', transcript):
                    if speaker not in speaker_transcripts:
                        speaker_transcripts[speaker] = []
                    speaker_transcripts[speaker].append(transcript)
            group_speaker_map = speaker_map[speaker_map['idGp'] == group_id]
            if group_speaker_map.empty:
                return
            for speaker, texts in speaker_transcripts.items():
                transcript = " ".join(texts)
                if 'Male' in speaker:
                    gender = 'Male'
                    match = re.search(r'Male (\d+)', speaker)
                    track_id = int(match.group(1)) if match else 0
                elif 'Female' in speaker:
                    gender = 'Female'
                    match = re.search(r'Female (\d+)', speaker)
                    track_id = int(match.group(1)) if match else 0
                else:
                    continue
                match = group_speaker_map[(group_speaker_map['GenderValue'] == (2 if gender == 'Female' else 1)) &
                                         (group_speaker_map['idTRack'] == track_id)]
                if not match.empty:
                    letter_id = match['Letter'].iloc[0]
                    transcriptions.append({
                        'group': group_id,
                        'letterId': letter_id,
                        'transcript': transcript
                    })
    except Exception as e:
        print(f"Error processing file {file_path}: {e}")

# Extract group number and process files
for txt_file in trans_folder_path.glob('*.txt'):
    group_id_match = re.search(r'group\s*(\d+)', txt_file.name, re.IGNORECASE)
    if group_id_match:
        group_id = int(group_id_match.group(1))
        extract_transcripts(txt_file, group_id, letter_map_file)
    else:
        print(f"Skipping file {txt_file.name}: No group ID found")

transcription_df = pd.DataFrame(transcriptions)
transcription_df.to_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/transcriptions_combined.csv', index=False)

# Merge transcripts with master_df
master_df = pd.read_csv('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/combined_features.csv')
master_df['group'] = pd.to_numeric(master_df['group'], errors='coerce')
master_df = master_df.merge(transcription_df, how='left', on=['group', 'letterId'])
master_df['transcript'] = master_df['transcript'].fillna('')
updated_df_path = '/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/combined_features_with_transcripts.csv'
master_df.to_csv(updated_df_path, index=False)

master_df.columns
master_df.shape

# Split dataset by gender
male_data = master_df[master_df['Gender'] == 'Male']
female_data = master_df[master_df['Gender'] == 'Female']
all_data = master_df.copy()

# Target columns (Big Five personality traits)
target_cols = ['EXTROV.MEDIA.NEO', 'NEUROTIC.MEDIA.NEO', 'OPENNESS.MEDIA.NEO',
               'AGREAB.MEDIA.NEO', 'CONSCIENT.MEDIA.NEO']

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, mean_absolute_error
from transformers import DistilBertTokenizer, DistilBertModel
import torch
import shap
from scipy.stats import ttest_ind, f_oneway
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import ttest_ind, f_oneway, ks_2samp
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

"""# Text - Based Modeling"""

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
def tokenize_text(texts, max_length=512):
    # Tokenize all texts at once to ensure consistent padding
    encodings = tokenizer(
        texts.tolist(),  # Convert pandas Series to list
        truncation=True,
        padding='max_length',  # Pad to max_length
        max_length=max_length,
        return_tensors='pt'
    )
    return encodings['input_ids'], encodings['attention_mask']

class DistilBERTPersonality(torch.nn.Module):
    def __init__(self):
        super(DistilBERTPersonality, self).__init__()
        self.distilbert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.fc = torch.nn.Linear(768, 5)  # 5 for Big Five personality traits

    def forward(self, input_ids, attention_mask):
        outputs = self.distilbert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state[:, 0]
        return self.fc(pooled_output)

def train_text_model(data, target_cols, batch_size=8):
    model = DistilBERTPersonality().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)
    criterion = torch.nn.MSELoss()

    input_ids, attention_mask = tokenize_text(data['transcript'])
    if input_ids is None:
        raise ValueError("Tokenization failed")
    targets = torch.tensor(data[target_cols].values, dtype=torch.float32).to(device)

    model.train()
    for i in range(0, len(data), batch_size):
        batch_input_ids = input_ids[i:i+batch_size]
        batch_attention_mask = attention_mask[i:i+batch_size]
        batch_targets = targets[i:i+batch_size]

        optimizer.zero_grad()
        outputs = model(batch_input_ids, batch_attention_mask)
        loss = criterion(outputs, batch_targets)
        loss.backward()
        optimizer.step()

    return model

def predict_text_model(model, data):
    input_ids, attention_mask = tokenize_text(data['transcript'])
    if input_ids is None:
        raise ValueError("Tokenization failed")
    model.eval()
    with torch.no_grad():
        preds = model(input_ids, attention_mask).cpu().numpy()
    return preds

"""# Acoustic Based Modeling"""

# Acoustic feature preprocessing
acoustic_features = ['pitch_mean', 'pitch_std', 'pitch_range', 'intensity_mean', 'intensity_std',
                     'spectral_centroid_mean', 'spectral_centroid_std', 'speaking_rate']
scaler = StandardScaler()

def preprocess_acoustic(data, features):
    try:
        data_subset = data[features].dropna()
        if data_subset.empty:
            raise ValueError("No valid acoustic data after dropping NaNs")
        scaled_features = scaler.fit_transform(data_subset)
        return pd.DataFrame(scaled_features, columns=features, index=data_subset.index)
    except Exception as e:
        return pd.DataFrame()

def train_acoustic_model(data, features, target_cols):
    X = preprocess_acoustic(data, features)
    if X.empty:
        raise ValueError("Acoustic preprocessing failed")
    y = data.loc[X.index, target_cols]
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model

def predict_acoustic_model(model, data, features):
    X = preprocess_acoustic(data, features)
    if X.empty:
        raise ValueError("Acoustic preprocessing failed")
    return model.predict(X)

"""# Late Fusion (Text + Acoustic)"""

from sklearn.linear_model import LinearRegression

def late_fusion(text_preds, acoustic_preds, y_true):
    try:
        X_fusion = np.hstack([text_preds, acoustic_preds])
        fusion_model = LinearRegression()
        fusion_model.fit(X_fusion, y_true)
        return fusion_model.predict(X_fusion)
    except Exception as e:
        return np.zeros_like(y_true)

"""# Evaluation"""

# Evaluation
def evaluate_model(y_true, y_pred):
    try:
        mae = mean_absolute_error(y_true, y_pred, multioutput='raw_values')
        return {'mae_per_trait': dict(zip(target_cols, mae)), 'mae_mean': mae.mean()}
    except Exception as e:
        return {'mae_per_trait': {col: np.nan for col in target_cols}, 'mae_mean': np.nan}

# Bias Analysis
def compute_shap_values(model, X):
    try:
        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(X)
        return shap_values
    except Exception as e:
        return None

def statistical_tests(male_errors, female_errors):
    try:
        t_stat, p_val = ttest_ind(male_errors, female_errors, equal_var=False)
        f_stat, p_val_anova = f_oneway(male_errors, female_errors)
        return {'t_test_p': p_val, 'anova_p': p_val_anova}
    except Exception as e:
        return {'t_test_p': np.nan, 'anova_p': np.nan}

def compute_spd(male_preds, female_preds):
    try:
        ks_stat, _ = ks_2samp(male_preds, female_preds)
        return ks_stat
    except Exception as e:
        print(f"Error in SPD computation: {e}")
        return np.nan

def compute_gnpd(male_preds, female_preds):
    try:
        n_m, n_f = len(male_preds), len(female_preds)
        sigma_m, sigma_f = np.std(male_preds), np.std(female_preds)
        norm_factor = np.sqrt(sigma_m**2 + sigma_f**2) + 1e-10
        if norm_factor == 0:
            return 0
        diff_sum = sum(abs(m - f) for m in male_preds for f in female_preds)
        return diff_sum / (n_m * n_f * norm_factor)
    except Exception as e:
        print(f"Error in GNPD computation: {e}")
        return np.nan

def compute_cfs(test_data_male, test_data_female, pred_cols, w1=0.5, w2=0.5):
    cfs_scores = {}
    for col in pred_cols:
        male_preds = test_data_male[col].dropna().values
        female_preds = test_data_female[col].dropna().values
        if len(male_preds) == 0 or len(female_preds) == 0:
            print(f"No valid predictions for {col}")
            cfs_scores[col.replace('pred_', '')] = np.nan
            continue
        spd = compute_spd(male_preds, female_preds)
        gnpd = compute_gnpd(male_preds, female_preds)
        cfs = w1 * spd + w2 * gnpd
        cfs_scores[col.replace('pred_', '')] = cfs
    return cfs_scores

"""# Execution"""

subsets = {'male': male_data, 'female': female_data, 'all': all_data}
results = {}
shap_values_dict = {}
errors = {}
test_data_dict = {}
pred_cols = [f'pred_{col}' for col in target_cols]

for subset_name, subset_data in subsets.items():
    # Split data
    train_data, test_data = train_test_split(subset_data, test_size=0.2, random_state=42)
    test_data = test_data.copy()  # Avoid SettingWithCopyWarning

    # Text-based model
    try:
        text_model = train_text_model(train_data, target_cols)
        text_preds = predict_text_model(text_model, test_data)
    except Exception as e:
        print(f"Error in text model for {subset_name}: {e}")
        text_preds = np.zeros((len(test_data), len(target_cols)))

    # Acoustic-based model
    try:
        acoustic_model = train_acoustic_model(train_data, acoustic_features, target_cols)
        acoustic_preds = predict_acoustic_model(acoustic_model, test_data, acoustic_features)
    except Exception as e:
        print(f"Error in acoustic model for {subset_name}: {e}")
        acoustic_preds = np.zeros((len(test_data), len(target_cols)))

    # Late fusion
    try:
        y_true = test_data[target_cols].values
        fusion_preds = late_fusion(text_preds, acoustic_preds, y_true)

        # Store predictions in test_data
        for i, col in enumerate(pred_cols):
            test_data[col] = fusion_preds[:, i]
    except Exception as e:
        print(f"Error in fusion model for {subset_name}: {e}")
        fusion_preds = np.zeros((len(test_data), len(target_cols)))
        for col in pred_cols:
            test_data[col] = np.zeros(len(test_data))

    # Store test_data for CFS calculation
    test_data_dict[subset_name] = test_data

    # Evaluate models
    results[subset_name] = {
        'text': evaluate_model(y_true, text_preds),
        'acoustic': evaluate_model(y_true, acoustic_preds),
        'fusion': evaluate_model(y_true, fusion_preds)
    }

    # Compute SHAP values
    shap_values = compute_shap_values(acoustic_model, preprocess_acoustic(test_data, acoustic_features))
    shap_values_dict[subset_name] = shap_values if shap_values is not None else []

    # Store errors
    errors[subset_name] = np.abs(y_true - fusion_preds).mean(axis=1)

# Statistical tests
male_errors = errors['male']
female_errors = errors['female']
bias_results = statistical_tests(male_errors, female_errors)

# Compute CFS using test data
cfs_results = compute_cfs(test_data_dict['male'], test_data_dict['female'], pred_cols)

# Print results
for subset_name, metrics in results.items():
    print(f"\nResults for {subset_name} subset:")
    for model_type, scores in metrics.items():
        print(f"{model_type.capitalize()} model:")
        print(f"  Mean MAE: {scores['mae_mean']:.4f}")
        print("  MAE per trait:")
        for trait, mae in scores['mae_per_trait'].items():
            print(f"    {trait}: {mae:.4f}")

print("\nBias analysis (p-values):")
print(f"T-test: {bias_results['t_test_p']:.4f}")
print(f"ANOVA: {bias_results['anova_p']:.4f}")

print("\nComposite Fairness Scores (Lower is Better):")
for trait, score in cfs_results.items():
    print(f"{trait}: {score:.4f}")

# Add this after the existing imports in your script
import seaborn as sns
import matplotlib.pyplot as plt
import shap
import os

# Set seaborn style for publication-quality plots
sns.set_style("whitegrid")
plt.rcParams['font.size'] = 8
plt.rcParams['axes.titlesize'] = 8
plt.rcParams['axes.labelsize'] = 8
plt.rcParams['legend.fontsize'] = 7
plt.rcParams['figure.dpi'] = 100

# SHAP Visualization
# Define personality traits for labeling
target_cols = ['Extraversion', 'Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness']
acoustic_features = ['pitch_mean', 'pitch_std', 'pitch_range', 'intensity_mean',
                     'intensity_std', 'spectral_centroid_mean', 'spectral_centroid_std', 'speaking_rate']

# Function to generate SHAP summary plots
def plot_shap_summary(shap_values, features, subset_name, target_cols, acoustic_features, save_path):
    for i, trait in enumerate(target_cols):
        plt.figure(figsize=(8, 6))
        shap.summary_plot(shap_values[:, :, i], features=features, feature_names=acoustic_features,
                         show=False, plot_type='bar', color=plt.cm.tab10(0))
        plt.title(f'SHAP Feature Importance for {trait} ({subset_name} Subset)')
        plt.tight_layout()
        plt.savefig(f'{save_path}/shap_summary_{subset_name.lower()}_{trait.lower()}.png', dpi=300, bbox_inches='tight')
        plt.close()

# Save directory for SHAP plots
save_path = '/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/shap_plots'
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Generate SHAP summary plots for each subset
for subset_name in ['male', 'female', 'all']:
    # Get preprocessed test data for the subset
    test_data_subset = train_test_split(subsets[subset_name], test_size=0.2, random_state=42)[1]
    X_test = preprocess_acoustic(test_data_subset, acoustic_features)
    plot_shap_summary(shap_values_dict[subset_name], X_test, subset_name.capitalize(),
                      target_cols, acoustic_features, save_path)

# Save SHAP values to NumPy files for reproducibility
for subset_name in ['male', 'female', 'all']:
    np.save(f'{save_path}/shap_values_{subset_name}.npy', shap_values_dict[subset_name])

import pandas as pd
import numpy as np
import os

# Define features and traits
acoustic_features = ['pitch_mean', 'pitch_std', 'pitch_range', 'intensity_mean',
                     'intensity_std', 'spectral_centroid_mean', 'spectral_centroid_std', 'speaking_rate']
target_cols = ['Extraversion', 'Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness']

# Function to create SHAP table for a subset
def create_shap_table(shap_values, features, traits, subset_name):
    """
    Create a table of mean absolute SHAP values for a given subset.

    Parameters:
    - shap_values: SHAP values array [n_samples, n_features, n_outputs]
    - features: List of feature names
    - traits: List of personality trait names
    - subset_name: Name of the subset ('Male', 'Female', 'Combined')

    Returns:
    - DataFrame with mean absolute SHAP values
    """
    # Compute mean absolute SHAP values across samples for each feature and trait
    mean_abs_shap = np.abs(shap_values).mean(axis=0)  # Shape: [n_features, n_outputs]

    # Create DataFrame
    df = pd.DataFrame(mean_abs_shap, index=features, columns=traits)
    df.index.name = 'Feature'
    df = df.round(4)  # Round to 4 decimal places for readability

    return df

# Save directory for SHAP tables
save_path = '/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/shap_tables'
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Generate and save SHAP tables for each subset
shap_tables = {}
for subset_name in ['male', 'female', 'all']:
    # Assuming shap_values_dict is available from your script
    shap_values = shap_values_dict[subset_name]
    shap_table = create_shap_table(shap_values, acoustic_features, target_cols, subset_name.capitalize())
    shap_tables[subset_name] = shap_table

    # Save as CSV
    shap_table.to_csv(f'{save_path}/shap_table_{subset_name}.csv')

    # Save as LaTeX for academic paper
    latex_table = shap_table.to_latex(float_format="%.4f", caption=f"Mean Absolute SHAP Values for Acoustic Features ({subset_name.capitalize()} Subset)",
                                     label=f"tab:shap_{subset_name}", position="htbp")
    with open(f'{save_path}/shap_table_{subset_name}.tex', 'w') as f:
        f.write(latex_table)

# Combine all subsets into a single table for comparison (optional)
combined_table = pd.concat(
    [shap_tables['male'].add_prefix('Male_'),
     shap_tables['female'].add_prefix('Female_'),
     shap_tables['all'].add_prefix('Combined_')],
    axis=1
)
combined_table.to_csv(f'{save_path}/shap_table_combined.csv')
latex_combined = combined_table.to_latex(float_format="%.4f", caption="Mean Absolute SHAP Values Across All Subsets",
                                        label="tab:shap_combined", position="htbp")
with open(f'{save_path}/shap_table_combined.tex', 'w') as f:
    f.write(latex_combined)

# Print tables for inspection
for subset_name, table in shap_tables.items():
    print(f"\nSHAP Table for {subset_name.capitalize()} Subset:")
    print(table)

print("\nCombined SHAP Table:")
print(combined_table)

