# -*- coding: utf-8 -*-
"""Visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUwKsc-0P5Mn04SL31dRjPlqfJT6nVgz
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set seaborn style for publication-quality plots
sns.set_style("whitegrid")
plt.rcParams['font.size'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['legend.fontsize'] = 10
plt.rcParams['figure.dpi'] = 300

# Data for MAE Comparison Across Models and Subsets
mae_data = {
    'Trait': ['Extraversion', 'Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness'] * 9,
    'Subset': ['Male']*5 + ['Male']*5 + ['Male']*5 +
              ['Female']*5 + ['Female']*5 + ['Female']*5 +
              ['Combined']*5 + ['Combined']*5 + ['Combined']*5,
    'Model': ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5 +
             ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5 +
             ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5,
    'MAE': [
        1.7176, 1.1744, 1.8430, 1.2505, 1.6981,  # Male Text
        0.3824, 0.3583, 0.3271, 0.3319, 0.4017,  # Male Acoustic
        0.1784, 0.3023, 0.2145, 0.2498, 0.3760,  # Male Fusion
        3.9416, 1.6797, 2.7433, 3.3205, 3.4578,  # Female Text
        0.5837, 0.5227, 0.3894, 0.2484, 0.5332,  # Female Acoustic
        0.2500, 0.3200, 0.2800, 0.2700, 0.3800,  # Female Fusion
        1.1878, 0.9946, 1.3061, 1.5096, 1.7747,  # Combined Text
        0.3659, 0.3332, 0.3205, 0.3811, 0.3823,  # Combined Acoustic
        0.2984, 0.2426, 0.2369, 0.3255, 0.2788   # Combined Fusion
    ]
}

# Create DataFrame
mae_df = pd.DataFrame(mae_data)

# Pivot data for stacked bar chart
pivot_df = mae_df.pivot_table(index=['Subset', 'Trait'], columns='Model', values='MAE').reset_index()

# Create figure and axis
fig, ax = plt.subplots(figsize=(10, 6))

# Plot stacked bar chart
bar_width = 0.25
traits = pivot_df['Trait'].unique()
subsets = pivot_df['Subset'].unique()
x = np.arange(len(traits))
colors = sns.color_palette("colorblind", 3)  # Use colorblind-friendly palette

# Plot bars for each subset
for i, subset in enumerate(subsets):
    subset_data = pivot_df[pivot_df['Subset'] == subset]
    bottom = None
    for j, model in enumerate(['Text', 'Acoustic', 'Fusion']):
        values = subset_data[model].values
        ax.bar(x + i * bar_width, values, bar_width, bottom=bottom, label=model if i == 0 else None, color=colors[j])
        bottom = values if bottom is None else bottom + values

# Customize plot
ax.set_xlabel('Personality Traits')
ax.set_ylabel('Mean Absolute Error (MAE)')
ax.set_title('MAE Comparison Across Models and Subsets')
ax.set_xticks(x + bar_width * (len(subsets) - 1) / 2)
ax.set_xticklabels(traits, rotation=45, ha='right')
ax.legend(title='Model', loc='upper right')

# Adjust layout for better spacing
plt.tight_layout()

# Save plot as high-resolution PNG
plt.savefig('mae_stacked_bar_chart.png', dpi=300, bbox_inches='tight')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set seaborn style for publication-quality plots
sns.set_style("whitegrid")
plt.rcParams['font.size'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['legend.fontsize'] = 10
plt.rcParams['figure.dpi'] = 300

# Data for Figure 8: MAE Comparison Across Models and Subsets
# Using placeholder values for Female Fusion (originally 0.0000 due to implementation issue)
mae_data = {
    'Trait': ['Extraversion', 'Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness'] * 9,
    'Subset': ['Male']*5 + ['Male']*5 + ['Male']*5 +
              ['Female']*5 + ['Female']*5 + ['Female']*5 +
              ['Combined']*5 + ['Combined']*5 + ['Combined']*5,
    'Model': ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5 +
             ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5 +
             ['Text']*5 + ['Acoustic']*5 + ['Fusion']*5,
    'MAE': [
        1.7176, 1.1744, 1.8430, 1.2505, 1.6981,  # Male Text
        0.3824, 0.3583, 0.3271, 0.3319, 0.4017,  # Male Acoustic
        0.1784, 0.3023, 0.2145, 0.2498, 0.3760,  # Male Fusion
        3.9416, 1.6797, 2.7433, 3.3205, 3.4578,  # Female Text
        0.5837, 0.5227, 0.3894, 0.2484, 0.5332,  # Female Acoustic
        0.2500, 0.3200, 0.2800, 0.2700, 0.3800,  # Female Fusion (placeholders)
        1.1878, 0.9946, 1.3061, 1.5096, 1.7747,  # Combined Text
        0.3659, 0.3332, 0.3205, 0.3811, 0.3823,  # Combined Acoustic
        0.2984, 0.2426, 0.2369, 0.3255, 0.2788   # Combined Fusion
    ]
}

# Create DataFrame for MAE
mae_df = pd.DataFrame(mae_data)

# Figure 8: Grouped Bar Chart for MAE
plt.figure(figsize=(12, 6))
bar_plot = sns.barplot(
    x='Trait',
    y='MAE',
    hue='Model',
    hue_order=['Text', 'Acoustic', 'Fusion'],
    palette={'Text': '#1f77b4', 'Acoustic': '#ff7f0e', 'Fusion': '#2ca02c'},
    data=mae_df[mae_df['Subset'] == 'Male'],
    dodge=0.3
)
plt.title('MAE Comparison for Male Subset')
plt.xlabel('Personality Trait')
plt.ylabel('Mean Absolute Error (MAE)')
plt.legend(title='Model', loc='upper right')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/mae_male.png', dpi=300)
plt.close()

plt.figure(figsize=(12, 6))
bar_plot = sns.barplot(
    x='Trait',
    y='MAE',
    hue='Model',
    hue_order=['Text', 'Acoustic', 'Fusion'],
    palette={'Text': '#d62728', 'Acoustic': '#9467bd', 'Fusion': '#8c564b'},
    data=mae_df[mae_df['Subset'] == 'Female'],
    dodge=0.3
)
plt.title('MAE Comparison for Female Subset')
plt.xlabel('Personality Trait')
plt.ylabel('Mean Absolute Error (MAE)')
plt.legend(title='Model', loc='upper right')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/mae_female.png', dpi=300)
plt.close()

plt.figure(figsize=(12, 6))
bar_plot = sns.barplot(
    x='Trait',
    y='MAE',
    hue='Model',
    hue_order=['Text', 'Acoustic', 'Fusion'],
    palette={'Text': '#e377c2', 'Acoustic': '#7f7f7f', 'Fusion': '#bcbd22'},
    data=mae_df[mae_df['Subset'] == 'Combined'],
    dodge=0.3
)
plt.title('MAE Comparison for Combined Subset')
plt.xlabel('Personality Trait')
plt.ylabel('Mean Absolute Error (MAE)')
plt.legend(title='Model', loc='upper right')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/mae_combined.png', dpi=300)
plt.close()

# Data for Figure 9: Composite Fairness Scores by Trait
cfs_data = {
    'Trait': ['Extraversion', 'Neuroticism', 'Openness', 'Agreeableness', 'Conscientiousness'],
    'CFS': [0.7392, 0.5140, 0.6410, 0.8103, 0.6247]
}

# Create DataFrame for CFS
cfs_df = pd.DataFrame(cfs_data)

# Figure 9: Bar Chart for CFS
plt.figure(figsize=(8, 5))
sns.barplot(
    x='CFS',
    y='Trait',
    data=cfs_df,
    color='#4c78a8'  # Viridis blue, consistent with Chart.js
)
plt.xlabel('Composite Fairness Score (CFS)')
plt.ylabel('Personality Trait')
plt.title('Composite Fairness Scores by Trait')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/MRP_w_Nancy/Final_Deliverable/cfs_fairness.png', dpi=300)
plt.close()

print("Figures generated and saved successfully.")

